import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReactQueryProvider } from "@/contexts/ReactQueryProvider";
import NextTopLoader from "nextjs-toploader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<ReactQueryProvider>
					<NextTopLoader
						color="#2299DD"
						initialPosition={0.08}
						crawlSpeed={200}
						height={7}
						crawl={true}
						showSpinner={true}
						easing="ease"
						speed={300}
						shadow="0 0 10px #2299DD,0 0 5px #2299DD"
						template='<div class="bar" role="bar"><div class="peg"></div></div> 
  <div class="spinner" role="spinner"><div class="spinner-icon"></div></div>'
						zIndex={1600}
						showAtBottom={false}
					/>
					{children}
				</ReactQueryProvider>
			</body>
		</html>
	);
}
