import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReactQueryProvider } from "@/contexts/ReactQueryProvider";
import NextTopLoader from "nextjs-toploader";
import Script from "next/script";
import { Toaster } from "react-hot-toast";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<Script src="https://unpkg.com/react-scan/dist/auto.global.js" />
			<body className={inter.className}>
				<ReactQueryProvider>
					<NextTopLoader
						color="#2299DD"
						initialPosition={0.08}
						crawlSpeed={200}
						height={7}
						crawl={true}
						showSpinner={true}
						easing="ease"
						speed={300}
						shadow="0 0 10px #2299DD,0 0 5px #2299DD"
						template='<div class="bar" role="bar"><div class="peg"></div></div> 
  <div class="spinner" role="spinner"><div class="spinner-icon"></div></div>'
						zIndex={1600}
						showAtBottom={false}
					/>
					{children}
					<Toaster
						position="bottom-right"
						toastOptions={{
							className: "bg-white text-black shadow-lg rounded-md",
						}}
						containerStyle={{
							top: 10,
							right: 10,
							bottom: 10,
							left: 10,
						}}
					/>
				</ReactQueryProvider>
			</body>
		</html>
	);
}
